"""RSTBackend: sphinx-needs RST files as durable storage.

Needs are stored as sphinx-needs directives in `memory/<type-plural>.rst`.
A needs.json index is generated on `rebuild_index` via sphinx build.
Concurrency: filelock around any read-modify-write sequence.

RST parsing uses a regex approach similar to ai_memory_protocol but with
added atomicity + locking. We do NOT run sphinx on every load — only on
explicit `rebuild_index`.
"""
from __future__ import annotations

import re
from datetime import UTC, datetime
from pathlib import Path

from filelock import FileLock

from papyrus.models import Confidence, Link, LinkType, Need, NeedType, Scope, Status
from papyrus.storage.base import StorageBackend

# Plural filename per NeedType. Keeps layout friendly to human browsing.
_FILE_BY_TYPE: dict[NeedType, str] = {
    NeedType.MEM: "observations",
    NeedType.DEC: "decisions",
    NeedType.FACT: "facts",
    NeedType.PREF: "preferences",
    NeedType.RISK: "risks",
    NeedType.GOAL: "goals",
    NeedType.Q: "questions",
}

_CONF_PY = '''"""Papyrus workspace — generated by `papyrus init`."""
project = "papyrus-workspace"
extensions = ["sphinx_needs"]
master_doc = "index"

needs_types = [
    {"directive": "mem",  "title": "Observation", "prefix": "MEM_",  "color": "#DDDDDD", "style": "node"},
    {"directive": "dec",  "title": "Decision",    "prefix": "DEC_",  "color": "#FEDD8E", "style": "node"},
    {"directive": "fact", "title": "Fact",        "prefix": "FACT_", "color": "#BFD8D2", "style": "node"},
    {"directive": "pref", "title": "Preference",  "prefix": "PREF_", "color": "#CDE7F0", "style": "node"},
    {"directive": "risk", "title": "Risk",        "prefix": "RISK_", "color": "#F4B7B5", "style": "node"},
    {"directive": "goal", "title": "Goal",        "prefix": "GOAL_", "color": "#C2E0C6", "style": "node"},
    {"directive": "q",    "title": "Question",    "prefix": "Q_",    "color": "#E8D5C4", "style": "node"},
]

# Rich link types (Papyrus + sphinx-needs standard interop).
needs_extra_links = [
    {"option": "relates",     "incoming": "related_by",      "outgoing": "relates"},
    {"option": "supports",    "incoming": "supported_by",    "outgoing": "supports"},
    {"option": "depends",     "incoming": "depended_by",     "outgoing": "depends"},
    {"option": "supersedes",  "incoming": "superseded_by",   "outgoing": "supersedes"},
    {"option": "contradicts", "incoming": "contradicted_by", "outgoing": "contradicts"},
    {"option": "extends",     "incoming": "extended_by",     "outgoing": "extends"},
    {"option": "derives",     "incoming": "derived_by",      "outgoing": "derives"},
]

# Allow lowercase segments (sphinx-needs default rejects them).
needs_id_regex = r"^[A-Za-z0-9_]{3,}$"

exclude_patterns = ["_build"]
'''

_INDEX_RST = """Papyrus workspace
==================

.. toctree::
   :maxdepth: 2
   :glob:

   memory/*
"""

_SECTION_HEADER = {
    "observations": "Observations\n============\n",
    "decisions":    "Decisions\n=========\n",
    "facts":        "Facts\n=====\n",
    "preferences":  "Preferences\n===========\n",
    "risks":        "Risks\n=====\n",
    "goals":        "Goals\n=====\n",
    "questions":    "Questions\n=========\n",
}

# Match a single sphinx-needs directive with metadata fields.
_NEED_RE = re.compile(
    r"^\.\.\s+(?P<type>mem|dec|fact|pref|risk|goal|q)::\s*(?P<title>.+?)\n"
    r"(?P<fields>(?:[ \t]{3,}:[^\n]+\n)+)"
    r"(?:[ \t]*\n)?"
    r"(?P<body>(?:[ \t]{3,}[^\n]*\n?)*)",
    re.MULTILINE,
)
_FIELD_RE = re.compile(r"[ \t]{3,}:(?P<name>[\w-]+):\s*(?P<value>.*)")


class RSTBackend(StorageBackend):
    """Store needs as sphinx-needs RST directives in `memory/*.rst`."""

    def __init__(self, workspace: Path) -> None:
        self.workspace = Path(workspace)
        self.memory_dir = self.workspace / "memory"
        self.lock_path = self.workspace / ".papyrus.lock"

    # --- Workspace lifecycle -------------------------------------------------

    def init_workspace(self, path: Path) -> None:
        path = Path(path)
        path.mkdir(parents=True, exist_ok=True)
        conf_py = path / "conf.py"
        if not conf_py.exists():
            conf_py.write_text(_CONF_PY)
        index_rst = path / "index.rst"
        if not index_rst.exists():
            index_rst.write_text(_INDEX_RST)
        (path / "memory").mkdir(exist_ok=True)
        for plural in _FILE_BY_TYPE.values():
            rst = path / "memory" / f"{plural}.rst"
            if not rst.exists():
                rst.write_text(_SECTION_HEADER[plural] + "\n")

    # --- Read ----------------------------------------------------------------

    def load_needs(self) -> list[Need]:
        if not self.memory_dir.exists():
            return []
        out: list[Need] = []
        for rst in sorted(self.memory_dir.glob("*.rst")):
            out.extend(self._parse_file(rst))
        out.sort(key=lambda n: n.created_at)
        return out

    def find_by_id(self, need_id: str) -> Need | None:
        for n in self.load_needs():
            if n.id == need_id:
                return n
        return None

    # --- Internal parsing ----------------------------------------------------

    def _parse_file(self, rst: Path) -> list[Need]:
        text = rst.read_text(encoding="utf-8", errors="ignore")
        found: list[Need] = []
        for m in _NEED_RE.finditer(text):
            fields = {
                fm.group("name"): fm.group("value").strip()
                for fm in _FIELD_RE.finditer(m.group("fields"))
            }
            need = self._build_need(m.group("type"), m.group("title").strip(), fields, m.group("body"))
            if need is not None:
                found.append(need)
        return found

    def _build_need(self, typ: str, title: str, fields: dict[str, str], body: str) -> Need | None:
        try:
            ntype = NeedType(typ)
            nid = fields.get("id", "").strip()
            if not nid:
                return None
            created = _parse_dt(fields.get("created_at")) or datetime.now(UTC)
            updated = _parse_dt(fields.get("updated_at")) or created
            return Need(
                id=nid,
                type=ntype,
                title=title,
                body=_dedent(body),
                tags=[t.strip() for t in fields.get("tags", "").split(",") if t.strip()],
                confidence=_enum_or(Confidence, fields.get("confidence"), Confidence.MEDIUM),
                scope=_enum_or(Scope, fields.get("scope"), Scope.LOCAL),
                status=_enum_or(Status, fields.get("status"), Status.ACTIVE),
                created_at=created,
                updated_at=updated,
                review_after=_parse_dt(fields.get("review_after")),
                source=fields.get("source", ""),
                links=_parse_links(fields),
            )
        except Exception:
            # Corrupt directive — skip rather than crash load.
            return None

    # --- Write / update / index ---------------------------------------------

    def append_need(self, need: Need) -> None:
        rst_path = self.memory_dir / f"{_FILE_BY_TYPE[need.type]}.rst"
        with FileLock(str(self.lock_path), timeout=30):
            existing = self.load_needs()
            if any(n.id == need.id for n in existing):
                raise ValueError(f"id {need.id!r} already exists")
            block = _render_need(need)
            current = rst_path.read_text(encoding="utf-8") if rst_path.exists() else ""
            if not current.endswith("\n"):
                current += "\n"
            rst_path.write_text(current + "\n" + block + "\n", encoding="utf-8")

    def update_need(self, need_id: str, **fields: object) -> Need:
        immutable = {"id", "type", "created_at"}
        bad = immutable & fields.keys()
        if bad:
            raise ValueError(f"immutable fields cannot be updated: {sorted(bad)}")

        with FileLock(str(self.lock_path), timeout=30):
            existing = self.load_needs()
            match_idx = next((i for i, n in enumerate(existing) if n.id == need_id), None)
            if match_idx is None:
                raise KeyError(need_id)

            current = existing[match_idx]
            patch = dict(fields)
            patch["updated_at"] = datetime.now(UTC)
            updated = current.model_copy(update=patch)

            # Rewrite the entire type-specific file with all needs of that type.
            plural = _FILE_BY_TYPE[current.type]
            rst_path = self.memory_dir / f"{plural}.rst"
            same_type = [n for n in existing if n.type == current.type]
            same_type[same_type.index(current)] = updated
            header = _SECTION_HEADER[plural]
            body = "\n\n".join(_render_need(n) for n in same_type)
            # .tmp orphan on mid-write crash is harmless: load_needs globs *.rst only.
            tmp_path = rst_path.with_suffix(rst_path.suffix + ".tmp")
            tmp_path.write_text(header + "\n" + body + "\n", encoding="utf-8")
            tmp_path.replace(rst_path)
            return updated

    def rebuild_index(self) -> int:
        import json

        with FileLock(str(self.lock_path), timeout=30):
            needs = self.load_needs()
            idx_dir = self.workspace / ".papyrus"
            idx_dir.mkdir(exist_ok=True)
            payload = {
                "version": 1,
                "generated_at": datetime.now(UTC).isoformat(),
                "needs": [n.model_dump(mode="json") for n in needs],
            }
            (idx_dir / "index.json").write_text(json.dumps(payload, indent=2))

            # Optional semantic reindex; silently skipped when extra missing.
            # The broad except wraps semantic_available() too so that a broken
            # sentence-transformers install (e.g. import raises something other
            # than ImportError — CUDA init, version mismatch) can never block
            # the base JSON rebuild. Papyrus has no logger yet, so this swallow
            # is currently unobservable — revisit when we add structured logging.
            from papyrus import semantic as _semantic
            try:
                if _semantic.semantic_available():
                    sem_idx = _semantic.build_default_index(self.workspace)
                    sem_idx.reindex(needs)
            except Exception:  # noqa: BLE001
                pass

            return len(needs)


# --- Helpers -----------------------------------------------------------------

def _parse_dt(raw: str | None) -> datetime | None:
    if not raw:
        return None
    try:
        return datetime.fromisoformat(raw.replace("Z", "+00:00"))
    except ValueError:
        return None


def _dedent(text: str) -> str:
    lines = [ln[3:] if ln.startswith("   ") else ln for ln in text.splitlines()]
    return "\n".join(lines).strip()


def _enum_or(enum_cls, raw: str | None, default):  # type: ignore[no-untyped-def]
    if raw:
        try:
            return enum_cls(raw.strip())
        except ValueError:
            pass
    return default


def _parse_links(fields: dict[str, str]) -> list[Link]:
    out: list[Link] = []
    for lt in LinkType:
        raw = fields.get(lt.value, "")
        for tgt in (t.strip() for t in raw.split(",") if t.strip()):
            out.append(Link(type=lt, target=tgt))
    return out


def _render_need(n: Need) -> str:
    def _fmt_dt(dt: datetime) -> str:
        return dt.astimezone(UTC).isoformat().replace("+00:00", "Z")

    lines: list[str] = [f".. {n.type.value}:: {n.title}"]
    lines.append(f"   :id: {n.id}")
    lines.append(f"   :status: {n.status.value}")
    lines.append(f"   :confidence: {n.confidence.value}")
    lines.append(f"   :scope: {n.scope.value}")
    lines.append(f"   :created_at: {_fmt_dt(n.created_at)}")
    lines.append(f"   :updated_at: {_fmt_dt(n.updated_at)}")
    if n.review_after:
        lines.append(f"   :review_after: {_fmt_dt(n.review_after)}")
    if n.tags:
        lines.append(f"   :tags: {','.join(n.tags)}")
    if n.source:
        lines.append(f"   :source: {n.source}")

    # Group links by type for :relates: foo,bar format
    by_type: dict[LinkType, list[str]] = {lt: [] for lt in LinkType}
    for lk in n.links:
        by_type[lk.type].append(lk.target)
    for lt in LinkType:
        if by_type[lt]:
            lines.append(f"   :{lt.value}: {','.join(by_type[lt])}")

    # Body: indent by 3 spaces, blank line between header and body
    body = n.body.strip()
    if body:
        lines.append("")
        for ln in body.splitlines():
            lines.append("   " + ln if ln else "")
    return "\n".join(lines)
